// Code generated by gocc; DO NOT EDIT.

package token

import (
	"fmt"
	"strconv"
	"unicode/utf8"
)

type Token struct {
	Type
	Lit []byte
	Pos
}

type Type int

const (
	INVALID Type = iota
	EOF
)

type Pos struct {
	Offset int
	Line   int
	Column int
}

func (p Pos) String() string {
	return fmt.Sprintf("Pos(offset=%d, line=%d, column=%d)", p.Offset, p.Line, p.Column)
}

type TokenMap struct {
	typeMap []string
	idMap   map[string]Type
}

func (m TokenMap) Id(tok Type) string {
	if int(tok) < len(m.typeMap) {
		return m.typeMap[tok]
	}
	return "unknown"
}

func (m TokenMap) Type(tok string) Type {
	if typ, exist := m.idMap[tok]; exist {
		return typ
	}
	return INVALID
}

func (m TokenMap) TokenString(tok *Token) string {
	return fmt.Sprintf("%s(%d,%s)", m.Id(tok.Type), tok.Type, tok.Lit)
}

func (m TokenMap) StringType(typ Type) string {
	return fmt.Sprintf("%s(%d)", m.Id(typ), typ)
}

// CharLiteralValue returns the string value of the char literal.
func (t *Token) CharLiteralValue() string {
	return string(t.Lit[1 : len(t.Lit)-1])
}

// Float32Value returns the float32 value of the token or an error if the token literal does not
// denote a valid float32.
func (t *Token) Float32Value() (float32, error) {
	if v, err := strconv.ParseFloat(string(t.Lit), 32); err != nil {
		return 0, err
	} else {
		return float32(v), nil
	}
}

// Float64Value returns the float64 value of the token or an error if the token literal does not
// denote a valid float64.
func (t *Token) Float64Value() (float64, error) {
	return strconv.ParseFloat(string(t.Lit), 64)
}

// IDValue returns the string representation of an identifier token.
func (t *Token) IDValue() string {
	return string(t.Lit)
}

// Int32Value returns the int32 value of the token or an error if the token literal does not
// denote a valid float64.
func (t *Token) Int32Value() (int32, error) {
	if v, err := strconv.ParseInt(string(t.Lit), 10, 64); err != nil {
		return 0, err
	} else {
		return int32(v), nil
	}
}

// Int64Value returns the int64 value of the token or an error if the token literal does not
// denote a valid float64.
func (t *Token) Int64Value() (int64, error) {
	return strconv.ParseInt(string(t.Lit), 10, 64)
}

// UTF8Rune decodes the UTF8 rune in the token literal. It returns utf8.RuneError if
// the token literal contains an invalid rune.
func (t *Token) UTF8Rune() (rune, error) {
	r, _ := utf8.DecodeRune(t.Lit)
	if r == utf8.RuneError {
		err := fmt.Errorf("Invalid rune")
		return r, err
	}
	return r, nil
}

// StringValue returns the string value of the token literal.
func (t *Token) StringValue() string {
	return string(t.Lit[1 : len(t.Lit)-1])
}

var TokMap = TokenMap{
	typeMap: []string{
		"INVALID",
		"$",
		"program",
		"id",
		"semicolon",
		"leftbracket",
		"rightbracket",
		"empty",
		"comma",
		"leftparenthesis",
		"rightparenthesis",
		"voidtype",
		"inttype",
		"floattype",
		"booltype",
		"stringtype",
		"chartype",
		"squaretype",
		"circletype",
		"imagetype",
		"texttype",
		"backgroundtype",
		"relop",
		"logicalop",
		"plus",
		"minus",
		"mult",
		"div",
		"equals",
		"print",
		"if",
		"else",
		"return",
		"for",
		"while",
		"cteint",
		"ctefloat",
		"ctestring",
		"ctechar",
		"ctebool",
		"leftsqrbracket",
		"rightsqrbracket",
		"list",
		"dot",
		"colon",
	},

	idMap: map[string]Type{
		"INVALID":          0,
		"$":                1,
		"program":          2,
		"id":               3,
		"semicolon":        4,
		"leftbracket":      5,
		"rightbracket":     6,
		"empty":            7,
		"comma":            8,
		"leftparenthesis":  9,
		"rightparenthesis": 10,
		"voidtype":         11,
		"inttype":          12,
		"floattype":        13,
		"booltype":         14,
		"stringtype":       15,
		"chartype":         16,
		"squaretype":       17,
		"circletype":       18,
		"imagetype":        19,
		"texttype":         20,
		"backgroundtype":   21,
		"relop":            22,
		"logicalop":        23,
		"plus":             24,
		"minus":            25,
		"mult":             26,
		"div":              27,
		"equals":           28,
		"print":            29,
		"if":               30,
		"else":             31,
		"return":           32,
		"for":              33,
		"while":            34,
		"cteint":           35,
		"ctefloat":         36,
		"ctestring":        37,
		"ctechar":          38,
		"ctebool":          39,
		"leftsqrbracket":   40,
		"rightsqrbracket":  41,
		"list":             42,
		"dot":              43,
		"colon":            44,
	},
}
