// Code generated by gocc; DO NOT EDIT.

package parser

import "github.com/sdkvictor/golang-compiler/ast"

type (
	ProdTab      [numProductions]ProdTabEntry
	ProdTabEntry struct {
		String     string
		Id         string
		NTType     int
		Index      int
		NumSymbols int
		ReduceFunc func([]Attrib) (Attrib, error)
	}
	Attrib interface {
	}
)

var productionsTable = ProdTab{
	ProdTabEntry{
		String: `S' : Programa	<<  >>`,
		Id:         "S'",
		NTType:     0,
		Index:      0,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `Programa : program id semicolon leftbracket VarsOp rightbracket Functions	<< ast.NewProgram(X[1], X[4], X[6]) >>`,
		Id:         "Programa",
		NTType:     1,
		Index:      1,
		NumSymbols: 7,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return ast.NewProgram(X[1], X[4], X[6])
		},
	},
	ProdTabEntry{
		String: `VarsOp : Vars	<<  >>`,
		Id:         "VarsOp",
		NTType:     2,
		Index:      2,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `VarsOp : empty	<<  >>`,
		Id:         "VarsOp",
		NTType:     2,
		Index:      3,
		NumSymbols: 0,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return nil, nil
		},
	},
	ProdTabEntry{
		String: `Vars : Type Ids semicolon Vars	<<  >>`,
		Id:         "Vars",
		NTType:     3,
		Index:      4,
		NumSymbols: 4,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `Vars : Type Ids semicolon	<<  >>`,
		Id:         "Vars",
		NTType:     3,
		Index:      5,
		NumSymbols: 3,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `Ids : id comma Ids	<<  >>`,
		Id:         "Ids",
		NTType:     4,
		Index:      6,
		NumSymbols: 3,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `Ids : id	<<  >>`,
		Id:         "Ids",
		NTType:     4,
		Index:      7,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `Params : ParamsAux	<<  >>`,
		Id:         "Params",
		NTType:     5,
		Index:      8,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `Params : empty	<<  >>`,
		Id:         "Params",
		NTType:     5,
		Index:      9,
		NumSymbols: 0,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return nil, nil
		},
	},
	ProdTabEntry{
		String: `ParamsAux : Type id comma ParamsAux	<< ast.AppendParamsList(X[0], X[1], X[3]) >>`,
		Id:         "ParamsAux",
		NTType:     6,
		Index:      10,
		NumSymbols: 4,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return ast.AppendParamsList(X[0], X[1], X[3])
		},
	},
	ProdTabEntry{
		String: `ParamsAux : Type id	<< ast.NewParamsList(X[0], X[1]) >>`,
		Id:         "ParamsAux",
		NTType:     6,
		Index:      11,
		NumSymbols: 2,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return ast.NewParamsList(X[0], X[1])
		},
	},
	ProdTabEntry{
		String: `Functions : FunctionsAux id leftparenthesis Params rightparenthesis Block Functions	<< ast.AppendFunctionList(X[0], X[1], X[3], X[5], X[6]) >>`,
		Id:         "Functions",
		NTType:     7,
		Index:      12,
		NumSymbols: 7,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return ast.AppendFunctionList(X[0], X[1], X[3], X[5], X[6])
		},
	},
	ProdTabEntry{
		String: `Functions : FunctionsAux id leftparenthesis Params rightparenthesis Block	<< ast.FirstFunction(X[0], X[1], X[3], X[5]) >>`,
		Id:         "Functions",
		NTType:     7,
		Index:      13,
		NumSymbols: 6,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return ast.FirstFunction(X[0], X[1], X[3], X[5])
		},
	},
	ProdTabEntry{
		String: `FunctionsAux : Type	<< ast.NewType(X[0]) >>`,
		Id:         "FunctionsAux",
		NTType:     8,
		Index:      14,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return ast.NewType(X[0])
		},
	},
	ProdTabEntry{
		String: `FunctionsAux : voidtype	<< ast.NewType(X[0]) >>`,
		Id:         "FunctionsAux",
		NTType:     8,
		Index:      15,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return ast.NewType(X[0])
		},
	},
	ProdTabEntry{
		String: `Block : leftbracket BlockAux rightbracket	<<  >>`,
		Id:         "Block",
		NTType:     9,
		Index:      16,
		NumSymbols: 3,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `Block : leftbracket rightbracket	<<  >>`,
		Id:         "Block",
		NTType:     9,
		Index:      17,
		NumSymbols: 2,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `BlockAux : Statement	<< ast.NewStatementList(X[0]) >>`,
		Id:         "BlockAux",
		NTType:     10,
		Index:      18,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return ast.NewStatementList(X[0])
		},
	},
	ProdTabEntry{
		String: `BlockAux : Statement BlockAux	<< ast.AppendStatement(X[0], X[1]) >>`,
		Id:         "BlockAux",
		NTType:     10,
		Index:      19,
		NumSymbols: 2,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return ast.AppendStatement(X[0], X[1])
		},
	},
	ProdTabEntry{
		String: `Statement : Vars	<< ast.NewStatement(X[0]) >>`,
		Id:         "Statement",
		NTType:     11,
		Index:      20,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return ast.NewStatement(X[0])
		},
	},
	ProdTabEntry{
		String: `Statement : Assign	<< ast.NewStatement(X[0]) >>`,
		Id:         "Statement",
		NTType:     11,
		Index:      21,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return ast.NewStatement(X[0])
		},
	},
	ProdTabEntry{
		String: `Statement : Condition	<< ast.NewStatement(X[0]) >>`,
		Id:         "Statement",
		NTType:     11,
		Index:      22,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return ast.NewStatement(X[0])
		},
	},
	ProdTabEntry{
		String: `Statement : Return	<< ast.NewStatement(X[0]) >>`,
		Id:         "Statement",
		NTType:     11,
		Index:      23,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return ast.NewStatement(X[0])
		},
	},
	ProdTabEntry{
		String: `Statement : For	<< ast.NewStatement(X[0]) >>`,
		Id:         "Statement",
		NTType:     11,
		Index:      24,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return ast.NewStatement(X[0])
		},
	},
	ProdTabEntry{
		String: `Statement : While	<< ast.NewStatement(X[0]) >>`,
		Id:         "Statement",
		NTType:     11,
		Index:      25,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return ast.NewStatement(X[0])
		},
	},
	ProdTabEntry{
		String: `Statement : CallFunction semicolon	<< ast.NewStatement(X[0]) >>`,
		Id:         "Statement",
		NTType:     11,
		Index:      26,
		NumSymbols: 2,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return ast.NewStatement(X[0])
		},
	},
	ProdTabEntry{
		String: `Statement : CallClassFunction semicolon	<< ast.NewStatement(X[0]) >>`,
		Id:         "Statement",
		NTType:     11,
		Index:      27,
		NumSymbols: 2,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return ast.NewStatement(X[0])
		},
	},
	ProdTabEntry{
		String: `BasicType : inttype	<< ast.NewType(X[0]) >>`,
		Id:         "BasicType",
		NTType:     12,
		Index:      28,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return ast.NewType(X[0])
		},
	},
	ProdTabEntry{
		String: `BasicType : floattype	<< ast.NewType(X[0]) >>`,
		Id:         "BasicType",
		NTType:     12,
		Index:      29,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return ast.NewType(X[0])
		},
	},
	ProdTabEntry{
		String: `BasicType : booltype	<< ast.NewType(X[0]) >>`,
		Id:         "BasicType",
		NTType:     12,
		Index:      30,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return ast.NewType(X[0])
		},
	},
	ProdTabEntry{
		String: `BasicType : stringtype	<< ast.NewType(X[0]) >>`,
		Id:         "BasicType",
		NTType:     12,
		Index:      31,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return ast.NewType(X[0])
		},
	},
	ProdTabEntry{
		String: `BasicType : Object	<< ast.NewType(X[0]) >>`,
		Id:         "BasicType",
		NTType:     12,
		Index:      32,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return ast.NewType(X[0])
		},
	},
	ProdTabEntry{
		String: `Object : squaretype	<< ast.NewType(X[0]) >>`,
		Id:         "Object",
		NTType:     13,
		Index:      33,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return ast.NewType(X[0])
		},
	},
	ProdTabEntry{
		String: `Object : circletype	<< ast.NewType(X[0]) >>`,
		Id:         "Object",
		NTType:     13,
		Index:      34,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return ast.NewType(X[0])
		},
	},
	ProdTabEntry{
		String: `Object : imagetype	<< ast.NewType(X[0]) >>`,
		Id:         "Object",
		NTType:     13,
		Index:      35,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return ast.NewType(X[0])
		},
	},
	ProdTabEntry{
		String: `Object : texttype	<< ast.NewType(X[0]) >>`,
		Id:         "Object",
		NTType:     13,
		Index:      36,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return ast.NewType(X[0])
		},
	},
	ProdTabEntry{
		String: `Object : backgroundtype	<< ast.NewType(X[0]) >>`,
		Id:         "Object",
		NTType:     13,
		Index:      37,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return ast.NewType(X[0])
		},
	},
	ProdTabEntry{
		String: `Expression : Exp	<< ast.NewExpression(X[0]) >>`,
		Id:         "Expression",
		NTType:     14,
		Index:      38,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return ast.NewExpression(X[0])
		},
	},
	ProdTabEntry{
		String: `Expression : Exp Operations Expression	<< ast.AppendExpression(X[0], X[1], X[2]) >>`,
		Id:         "Expression",
		NTType:     14,
		Index:      39,
		NumSymbols: 3,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return ast.AppendExpression(X[0], X[1], X[2])
		},
	},
	ProdTabEntry{
		String: `Operations : relop	<<  >>`,
		Id:         "Operations",
		NTType:     15,
		Index:      40,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `Operations : logicalop	<<  >>`,
		Id:         "Operations",
		NTType:     15,
		Index:      41,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `Exp : Term	<<  >>`,
		Id:         "Exp",
		NTType:     16,
		Index:      42,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `Exp : Term plus Exp	<<  >>`,
		Id:         "Exp",
		NTType:     16,
		Index:      43,
		NumSymbols: 3,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `Exp : Term minus Exp	<<  >>`,
		Id:         "Exp",
		NTType:     16,
		Index:      44,
		NumSymbols: 3,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `Term : Factor	<<  >>`,
		Id:         "Term",
		NTType:     17,
		Index:      45,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `Term : Factor mult Term	<<  >>`,
		Id:         "Term",
		NTType:     17,
		Index:      46,
		NumSymbols: 3,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `Term : Factor div Term	<<  >>`,
		Id:         "Term",
		NTType:     17,
		Index:      47,
		NumSymbols: 3,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `Factor : leftparenthesis Expression rightparenthesis	<<  >>`,
		Id:         "Factor",
		NTType:     18,
		Index:      48,
		NumSymbols: 3,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `Factor : plus Varcte	<<  >>`,
		Id:         "Factor",
		NTType:     18,
		Index:      49,
		NumSymbols: 2,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `Factor : minus Varcte	<<  >>`,
		Id:         "Factor",
		NTType:     18,
		Index:      50,
		NumSymbols: 2,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `Factor : Varcte	<<  >>`,
		Id:         "Factor",
		NTType:     18,
		Index:      51,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `Assign : id equals Expression semicolon	<< ast.NewAssign(X[0], nil, X[1], X[2]) >>`,
		Id:         "Assign",
		NTType:     19,
		Index:      52,
		NumSymbols: 4,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return ast.NewAssign(X[0], nil, X[1], X[2])
		},
	},
	ProdTabEntry{
		String: `Assign : Attribute equals Expression semicolon	<< ast.NewAssign(nil, X[0], X[1], X[2]) >>`,
		Id:         "Assign",
		NTType:     19,
		Index:      53,
		NumSymbols: 4,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return ast.NewAssign(nil, X[0], X[1], X[2])
		},
	},
	ProdTabEntry{
		String: `Condition : if leftparenthesis Expression rightparenthesis Block	<< ast.NewCondition(X[0], X[2], X[4], nil) >>`,
		Id:         "Condition",
		NTType:     20,
		Index:      54,
		NumSymbols: 5,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return ast.NewCondition(X[0], X[2], X[4], nil)
		},
	},
	ProdTabEntry{
		String: `Condition : if leftparenthesis Expression rightparenthesis Block else Block	<< ast.NewCondition(X[0], X[2], X[4], X[6] ) >>`,
		Id:         "Condition",
		NTType:     20,
		Index:      55,
		NumSymbols: 7,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return ast.NewCondition(X[0], X[2], X[4], X[6] )
		},
	},
	ProdTabEntry{
		String: `Return : return Expression semicolon	<< ast.NewReturn(X[0], X[1]) >>`,
		Id:         "Return",
		NTType:     21,
		Index:      56,
		NumSymbols: 3,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return ast.NewReturn(X[0], X[1])
		},
	},
	ProdTabEntry{
		String: `For : for leftparenthesis Assign semicolon Expression semicolon Expression semicolon rightparenthesis Block	<< ast.NewFor(X[0], X[2], X[4], X[6], X[9]) >>`,
		Id:         "For",
		NTType:     22,
		Index:      57,
		NumSymbols: 10,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return ast.NewFor(X[0], X[2], X[4], X[6], X[9])
		},
	},
	ProdTabEntry{
		String: `While : while leftparenthesis Expression rightparenthesis Block	<< ast.NewWhile(X[0], X[2], X[4]) >>`,
		Id:         "While",
		NTType:     23,
		Index:      58,
		NumSymbols: 5,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return ast.NewWhile(X[0], X[2], X[4])
		},
	},
	ProdTabEntry{
		String: `CallFunction : id leftparenthesis CallFunctionAux rightparenthesis	<< ast.NewFunctionCall(X[0], X[2]) >>`,
		Id:         "CallFunction",
		NTType:     24,
		Index:      59,
		NumSymbols: 4,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return ast.NewFunctionCall(X[0], X[2])
		},
	},
	ProdTabEntry{
		String: `CallFunction : id leftparenthesis rightparenthesis	<< ast.NewFunctionCall(X[0], nil) >>`,
		Id:         "CallFunction",
		NTType:     24,
		Index:      60,
		NumSymbols: 3,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return ast.NewFunctionCall(X[0], nil)
		},
	},
	ProdTabEntry{
		String: `CallClassFunction : id dot id leftparenthesis CallFunctionAux rightparenthesis	<< ast.NewFunctionCallClass(X[0], X[2], X[4]) >>`,
		Id:         "CallClassFunction",
		NTType:     25,
		Index:      61,
		NumSymbols: 6,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return ast.NewFunctionCallClass(X[0], X[2], X[4])
		},
	},
	ProdTabEntry{
		String: `CallClassFunction : id dot id leftparenthesis rightparenthesis	<< ast.NewFunctionCallClass(X[0], X[2], nil) >>`,
		Id:         "CallClassFunction",
		NTType:     25,
		Index:      62,
		NumSymbols: 5,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return ast.NewFunctionCallClass(X[0], X[2], nil)
		},
	},
	ProdTabEntry{
		String: `CallFunctionAux : Expression	<<  >>`,
		Id:         "CallFunctionAux",
		NTType:     26,
		Index:      63,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `CallFunctionAux : Expression comma CallFunctionAux	<<  >>`,
		Id:         "CallFunctionAux",
		NTType:     26,
		Index:      64,
		NumSymbols: 3,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `Varcte : id	<<  >>`,
		Id:         "Varcte",
		NTType:     27,
		Index:      65,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `Varcte : cteint	<< ast.NewConstantInt(X[0]) >>`,
		Id:         "Varcte",
		NTType:     27,
		Index:      66,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return ast.NewConstantInt(X[0])
		},
	},
	ProdTabEntry{
		String: `Varcte : ctefloat	<< ast.NewConstantFloat(X[0]) >>`,
		Id:         "Varcte",
		NTType:     27,
		Index:      67,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return ast.NewConstantFloat(X[0])
		},
	},
	ProdTabEntry{
		String: `Varcte : ctestring	<< ast.NewStringConstant(X[0]) >>`,
		Id:         "Varcte",
		NTType:     27,
		Index:      68,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return ast.NewStringConstant(X[0])
		},
	},
	ProdTabEntry{
		String: `Varcte : ctechar	<< ast.NewConstantChar(X[0]) >>`,
		Id:         "Varcte",
		NTType:     27,
		Index:      69,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return ast.NewConstantChar(X[0])
		},
	},
	ProdTabEntry{
		String: `Varcte : ListElem	<<  >>`,
		Id:         "Varcte",
		NTType:     27,
		Index:      70,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `Varcte : ctebool	<< ast.NewConstantBool(X[0]) >>`,
		Id:         "Varcte",
		NTType:     27,
		Index:      71,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return ast.NewConstantBool(X[0])
		},
	},
	ProdTabEntry{
		String: `Varcte : Attribute	<<  >>`,
		Id:         "Varcte",
		NTType:     27,
		Index:      72,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `Varcte : CallFunction	<<  >>`,
		Id:         "Varcte",
		NTType:     27,
		Index:      73,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `Varcte : CallClassFunction	<<  >>`,
		Id:         "Varcte",
		NTType:     27,
		Index:      74,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `ListElem : id leftsqrbracket Expression rightsqrbracket	<<  >>`,
		Id:         "ListElem",
		NTType:     28,
		Index:      75,
		NumSymbols: 4,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `Type : BasicType	<< X[0], nil >>`,
		Id:         "Type",
		NTType:     29,
		Index:      76,
		NumSymbols: 1,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return X[0], nil
		},
	},
	ProdTabEntry{
		String: `Type : list leftsqrbracket BasicType rightsqrbracket	<< ast.AppendType(X[2]) >>`,
		Id:         "Type",
		NTType:     29,
		Index:      77,
		NumSymbols: 4,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return ast.AppendType(X[2])
		},
	},
	ProdTabEntry{
		String: `Attribute : id dot id	<< ast.NewAttribute(X[0], X[2]) >>`,
		Id:         "Attribute",
		NTType:     30,
		Index:      78,
		NumSymbols: 3,
		ReduceFunc: func(X []Attrib) (Attrib, error) {
			return ast.NewAttribute(X[0], X[2])
		},
	},
}
